//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Candidate
    {
        public int Candidate_Id { get; set; }
        public string Candidate_Name { get; set; }
        public string Address { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<byte> Gender { get; set; }
    }
}
